PUSH = org.commands.CommandPush
POP = org.commands.CommandPop
PRINT = org.commands.CommandPrint
+ = org.commands.CommandAdd
- = org.commands.CommandDiff
* = org.commands.CommandMult
/ = org.commands.CommandDiv
SQRT = org.commands.CommandSqrt
DEFINE = org.commands.CommandDefine